import { NextResponse } from "next/server"
import { deepseekJSON } from "@/lib/deepseek"
import { prisma } from "@/lib/prisma"

interface SeoFields {
  title: string
  description: string
  ogTitle: string
  ogDescription: string
  keywords: string
}

// POST { pageKey: string, locale: "en"|"el"|"de", context?: string }
// Returns SeoFields generated by DeepSeek for the given page & locale.
export async function POST(req: Request) {
  try {
    const { pageKey, locale, context } = await req.json()
    if (!pageKey || !locale) {
      return NextResponse.json({ error: "pageKey and locale are required" }, { status: 400 })
    }

    // Build rich context for DeepSeek
    let pageContext = context || ""
    if (!pageContext) {
      if (pageKey.startsWith("villa:")) {
        const slug = pageKey.replace("villa:", "")
        const villa = await prisma.villa.findUnique({
          where: { slug },
          include: {
            translations: true,
            rates: { orderBy: { sortOrder: "asc" } },
          },
        })
        if (villa) {
          const tr = villa.translations.find((t: any) => t.locale === locale) || villa.translations[0]
          pageContext = `Villa name: ${tr?.name || slug}. ${tr?.blurb || ""}. Bedrooms: ${villa.bedrooms}, guests: ${villa.guests}, area: ${villa.sqm}m². ${villa.rates[0] ? `Starting from €${villa.rates[0].weekly}/week.` : ""}`
        }
      } else if (pageKey.startsWith("location:")) {
        const slug = pageKey.replace("location:", "")
        const location = await prisma.location.findUnique({
          where: { slug },
          include: { translations: true },
        })
        if (location) {
          const tr = location.translations.find((t: any) => t.locale === locale) || location.translations[0]
          pageContext = `Location: ${tr?.name || slug} on Lefkada island, Greece. ${tr?.short || ""}. ${tr?.long || ""}`
        }
      }
    }

    const localeNames: Record<string, string> = { en: "English", el: "Greek", de: "German" }
    const localeName = localeNames[locale] || "English"

    const result = await deepseekJSON<SeoFields>(
      `You are an expert SEO specialist for Ionian Dream Villas, a luxury villa rental website on Lefkada island, Greece. Generate precise, compelling SEO metadata that will rank well on Google and attract high-intent travellers searching for luxury villa rentals in Greece.`,
      `Generate SEO metadata in ${localeName} for this page:

Page key: ${pageKey}
Page context: ${pageContext || "Ionian Dream Villas — luxury villa rentals on Lefkada island, Greece"}

Requirements:
- title: max 60 characters, include the key topic + brand/location. Do NOT include "Ionian Dream Villas" if the page key is "home"
- description: 140-155 characters, compelling, include a soft CTA
- ogTitle: same as title or a slightly catchier variant (max 60 chars)
- ogDescription: same as description (max 155 chars)
- keywords: 5-8 comma-separated terms, mix short and long-tail

Return ONLY valid JSON:
{
  "title": "...",
  "description": "...",
  "ogTitle": "...",
  "ogDescription": "...",
  "keywords": "..."
}`,
      800
    )

    return NextResponse.json(result)
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
