import { NextResponse } from "next/server"
import { deepseekJSON } from "@/lib/deepseek"
import { prisma } from "@/lib/prisma"

interface SeoFields {
  title: string
  description: string
  ogTitle: string
  ogDescription: string
  keywords: string
}

// POST { pageKey: string, locale: "en"|"el"|"de", context?: string }
// Returns SeoFields generated by DeepSeek for the given page & locale.
export async function POST(req: Request) {
  try {
    const { pageKey, locale, context } = await req.json()
    if (!pageKey || !locale) {
      return NextResponse.json({ error: "pageKey and locale are required" }, { status: 400 })
    }

    // Build rich context for DeepSeek
    let pageContext = context || ""
    if (!pageContext) {
      if (pageKey.startsWith("villa:")) {
        const slug = pageKey.replace("villa:", "")
        const villa = await prisma.villa.findUnique({
          where: { slug },
          include: {
            translations: true,
            rates: { orderBy: { sortOrder: "asc" } },
          },
        })
        if (villa) {
          const tr = villa.translations.find((t: any) => t.locale === locale) || villa.translations[0]
          pageContext = `Villa name: ${tr?.name || slug}. ${tr?.blurb || ""}. Bedrooms: ${villa.bedrooms}, guests: ${villa.guests}, area: ${villa.sqm}m². ${villa.rates[0] ? `Starting from €${villa.rates[0].weekly}/week.` : ""}`
        }
      } else if (pageKey.startsWith("location:")) {
        const slug = pageKey.replace("location:", "")
        const location = await prisma.location.findUnique({
          where: { slug },
          include: { translations: true },
        })
        if (location) {
          const tr = location.translations.find((t: any) => t.locale === locale) || location.translations[0]
          pageContext = `Location: ${tr?.name || slug} on Lefkada island, Greece. ${tr?.short || ""}. ${tr?.long || ""}`
        }
      }
    }

    const localeNames: Record<string, string> = { en: "English", el: "Greek", de: "German" }
    const localeName = localeNames[locale] || "English"

    const result = await deepseekJSON<SeoFields>(
      `You are a senior SEO strategist and native ${localeName} copywriter specialising in luxury travel and boutique hospitality. You write meta titles and descriptions that rank well on Google AND genuinely entice the right traveller to click — not keyword-stuffed filler, but precise, evocative copy that signals quality and exclusivity.

Write naturally in ${localeName} as a native speaker would. Avoid literal translations, anglicisms, or robotic phrasing.`,
      `Write SEO metadata in ${localeName} for this page of a luxury private villa rental website on Lefkada island, Greece:

Page: ${pageKey}
Context: ${pageContext || "Ionian Dream Villas — three private luxury villas on the western shore of Lefkada, Greece. Private pools, sea views, direct booking."}

Requirements:
- title: 50–60 chars. Lead with the key benefit or place name; end with brand/location if space allows.
- description: 140–155 chars. One compelling reason to click + a soft, natural CTA. Read it aloud — it should sound human.
- ogTitle: same as title or a slightly more emotive variant (≤60 chars).
- ogDescription: same quality as description (≤155 chars).
- keywords: 6–8 comma-separated terms. Mix branded, generic, and long-tail. Use ${localeName} terms searchers actually type.

Return ONLY valid JSON:
{ "title": "...", "description": "...", "ogTitle": "...", "ogDescription": "...", "keywords": "..." }`,
      800
    )

    return NextResponse.json(result)
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
